spring:
  application:
    name: Payment_module

  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: ${MODULE_GROUP_ID}

microservices:
  baseUrl: ${BASE_URL}

server:
  port: ${SERVICE_PORT}

receipt:
  expiration-minutes: ${RECEIPT_EXPIRATION_MINUTES}

message:
  ttl:
    seconds: ${MESSAGE_TTL_SECONDS}