spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME}:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true

service:
  module-name:
    address: ${ADDRESS_MODULE_NAME}
    product: ${PRODUCT_MODULE_NAME}
    product-category: ${PRODUCT_CATEGORY_MODULE_NAME}
    store: ${STORE_MODULE_NAME}
    stock: ${STOCK_MODULE_NAME}
    order: ${ORDER_MODULE_NAME}
    operation: ${OPERATION_MODULE_NAME}
    payment: ${PAYMENT_MODULE_NAME}
    shipment: ${SHIPMENT_MODULE_NAME}
    notification: ${SHOP_NOTIFIER_MODULE_NAME}